name: Publish Docker image
on:
  release:
    types: [published]

jobs:
  python_image:
    name: Push rsvisa-python image to Dockerhub
    uses: casabre/rsvisa-python/.github/workflows/docker_build.yml@main
    with:
      python-interpreter: python
      python-version: "[3.6, 3.7, 3.8, 3.9]"
    secrets:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}

  pypy_image:
    name: Push rsvisa-pypy image to Dockerhub
    uses: casabre/rsvisa-python/.github/workflows/docker_build.yml@main
    with:
      python-interpreter: pypy
      python-version: "[3.6, 3.7, 3.8]"
    secrets:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
