name: Publish Docker image
on:
  release:
    types: [published]

jobs:
  python_image:
    name: Push rsvisa-python image to Dockerhub
    uses: casabre/rsvisa-python/.github/workflows/docker_build.yml@main
    with:
      python-interpreter: python
      python-version: '["3.6-slim-buster", "3.6-buster", "3.6-slim-bullseye", "3.6-bullseye", "3.6-slim", "3.6", "3.7-slim-buster", "3.7-buster", "3.7-slim-bullseye", "3.7-bullseye", "3.7-slim", "3.7", "3.8-slim-buster", "3.8-buster", "3.8-slim-bullseye", "3.8-bullseye", "3.8-slim", "3.8", "3.9-slim-buster", "3.9-buster", "3.9-slim-bullseye", "3.9-bullseye", "3.9-slim", "3.9", "3.10-slim-buster", "3.10-buster", "3.10-slim-bullseye", "3.10-bullseye", "3.10-slim", "3.10"]'
    secrets:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}

  pypy_image:
    name: Push rsvisa-pypy image to Dockerhub
    uses: casabre/rsvisa-python/.github/workflows/docker_build.yml@main
    with:
      python-interpreter: pypy
      python-version: '["3.6-slim-buster", "3.6-buster", "3.6-slim-bullseye", "3.6-bullseye", "3.6-slim", "3.6", "3.7-slim-buster", "3.7-buster", "3.7-slim-bullseye", "3.7-bullseye", "3.7-slim", "3.7", "3.8-slim-buster", "3.8-buster", "3.8-slim-bullseye", "3.8-bullseye", "3.8-slim", "3.8"]'
    secrets:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
