name: Publish Docker image
on:
  workflow_call:
    inputs:
      python-interpreter:
        required: true
        type: string
      python-version:
        required: true
        type: string
    secrets:
      username:
        required: true
      password:
        required: true

jobs:
  build_image:
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJSON(inputs.python-version) }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@bb984efc561711aaa26e433c32c3521176eae55b
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@e5622373a38e60fb6d795a4421e56882f2d7a681
        with:
          images: my-docker-hub-namespace/my-docker-hub-repository

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create Tag
        run: |
          echo "build_tag=docker.io/casabre/rsvisa-${{ inputs.python-interpreter }}:${{ matrix.python-version }}" >> $GITHUB_ENV
          echo "Tag: ${{ env.build_tag }}"

      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          build-args: |
            PYTHON_INTERPRETER=${{ inputs.python-interpreter }}
            PYTHON_VERSION=${{ matrix.python-version }}
          tags: ${{ env.build_tag }}
          # tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
